---
abstract: ~
author: ~
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.910'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RavLog
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.800050
  Catalyst::Action::RenderView: 0
  Catalyst::Authentication::Credential::Password: 0
  Catalyst::Authentication::Store::DBIx::Class: 0
  Catalyst::Controller::FormBuilder: 0
  Catalyst::Plugin::Authentication: 0.10008
  Catalyst::Plugin::Cache: 0
  Catalyst::Plugin::Cache::FileCache: 0
  Catalyst::Plugin::Captcha: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::PageCache: 0
  Catalyst::Plugin::Server: 0
  Catalyst::Plugin::Server::XMLRPC: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::FastMmap: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::View::JSON: 0
  Catalyst::View::TT: 0
  Config::Any::YAML: 0
  DBIx::Class: 0
  DBIx::Class::TimeStamp: 0
  DateTime: 0
  DateTime::Format::MySQL: 0
  HTML::CalendarMonthSimple: 0
  JSON::Syck: 0
  SCGI: 0
  SQL::Translator: 0
  SQL::Translator::Producer: 0
  Scalar::Util::Clone: 0
  Switch: 0
  Text::Highlight: 0
  Text::Textile: 0
  XML::Feed: 0
  YAML: 0
version: 0.01
